### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by KongMingxi** [deepomicslab/SCOIT#1]
Hi,

Congrats and thanks for your nice work!
I am wondering if the code for importing:
`from scot.multi_omics_model import`
should be:
`from scoit.multi_omics_model import`

Best,

**Comment by wangruohan111** [comment]
Hi,

Yes, sorry for the typo. I have fixed the examples.
Thanks for your interest in SCOIT.

Best regards,
Ruohan

**Comment by KongMingxi** [comment]
> Hi,
> 
> Yes, sorry for the typo. I have fixed the examples. Thanks for your interest in SCOIT.
> 
> Best regards, Ruohan

Thanks! Actually, the "__inti__.py" has not changed. I am not sure if there are any other scripts need to be fixed?

**Comment by wangruohan111** [comment]
Hi, I have checked the scripts in GitHub and PyPI and have fixed them. It should work smoothly now.

Thanks again!

Best regards,
Ruohan

**Comment by KongMingxi** [comment]
Thanks for your help! It can be imported now!

**Comment by wangruohan111** [comment]
Good! I am going to close this issue. Please feel free to open another if you encounter any problems when using SCOIT.
