### ISSUE TITLE
How to return trained models

### ISSUE THREAD

**Issue by KongMingxi** [deepomicslab/SCOIT#2]
Hi,

Is there any way to get the trained models from sc_multi_omics.fit()?

Best,

Mingxi

**Comment by wangruohan111** [comment]
Hi, Mingxi,

SCOIT provides a sklearn-style model training pipeline, i.e., after running "sc_model.fit(data)", the trained parameters have already been reserved in "sc_model". You can use "sc_model.C", "sc_model.G", and so on, to obtain the trained parameters.

Best regards,
Ruohan
